permissions:
  pull-requests: write
  contents: read

jobs:
  code_review_job:
    run: python review.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-3.5-turbo"
          openai_temperature: 0.5
          openai_max_tokens: 2048
          mode: files
          language: en
          custom_prompt: ""